[package]
name = "aoc2021"
version = "0.1.0"
authors = ["tgaede <tg.foobar@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.34.0"
regex = "1.5.4"
lazy_static = "1.4.0"
